python -m pip install colorama
python -m pip install fileinput
python -m pip install requests
python -m pip install re
python -m pip install json
python -m pip install ctypes
python -m pip install time
python -m pip install watchdog
python -m pip install pystylw
python -m pip install discord_webhook
python -m pip install shutil
